INSERT INTO teeth (teethID, Description, teethName) VALUES (1, "Upper Right Central", "URCe");
INSERT INTO teeth (teethID, Description, teethName) VALUES (2, "Upper Right Lateral", "URL");
INSERT INTO teeth (teethID, Description, teethName) VALUES (3, "Upper Right Cuspid", "URCu");
INSERT INTO teeth (teethID, Description, teethName) VALUES (4, "Upper Right 1st Bicuspid", "UR1B");
INSERT INTO teeth (teethID, Description, teethName) VALUES (5, "Upper Right 2nd Bicuspid", "UR2B");
INSERT INTO teeth (teethID, Description, teethName) VALUES (6, "Upper Right 1st Molar", "UR1M");
INSERT INTO teeth (teethID, Description, teethName) VALUES (7, "Upper Right 2nd Molar", "UR2M");
INSERT INTO teeth (teethID, Description, teethName) VALUES (8, "Upper Right 3rd Molar (Wisdom)", "UR3M(W)");
INSERT INTO teeth (teethID, Description, teethName) VALUES (9, "Lower Right 3rd Molar (Wisdom)", "LR3M(W)");
INSERT INTO teeth (teethID, Description, teethName) VALUES (10, "Lower Right 2nd Molar", "LR2M");
INSERT INTO teeth (teethID, Description, teethName) VALUES (11, "Lower Right 1st Molar", "LR1M");
INSERT INTO teeth (teethID, Description, teethName) VALUES (12, "Lower Right 2nd Bicuspid", "LR2B");
INSERT INTO teeth (teethID, Description, teethName) VALUES (13, "Lower Right 1st Bicuspid", "LR1B");
INSERT INTO teeth (teethID, Description, teethName) VALUES (14, "Lower Right Cuspid", "LRCu");
INSERT INTO teeth (teethID, Description, teethName) VALUES (15, "Lower Right Lateral", "LRL");
INSERT INTO teeth (teethID, Description, teethName) VALUES (16, "Lower Right Central", "LRCe");
INSERT INTO teeth (teethID, Description, teethName) VALUES (17, "Upper Left Central", "ULCe");
INSERT INTO teeth (teethID, Description, teethName) VALUES (18, "Upper Left Lateral", "ULL");
INSERT INTO teeth (teethID, Description, teethName) VALUES (19, "Upper Left Cuspid", "ULCu");
INSERT INTO teeth (teethID, Description, teethName) VALUES (20, "Upper Left 1st Bicuspid", "UL1B");
INSERT INTO teeth (teethID, Description, teethName) VALUES (21, "Upper Left 2nd Bicuspid", "UL2B");
INSERT INTO teeth (teethID, Description, teethName) VALUES (22, "Upper Left 1st Molar", "UL1M");
INSERT INTO teeth (teethID, Description, teethName) VALUES (23, "Upper Left 2nd Molar", "UL2M");
INSERT INTO teeth (teethID, Description, teethName) VALUES (24, "Upper Left 3rd Molar (Wisdom)", "UL3M(W)");
INSERT INTO teeth (teethID, Description, teethName) VALUES (25, "Lower Left 3rd Molar (Wisdom)", "LL3M(W)");
INSERT INTO teeth (teethID, Description, teethName) VALUES (26, "Lower Left 2nd Molar", "LL2M");
INSERT INTO teeth (teethID, Description, teethName) VALUES (27, "Lower Left 1st Molar", "LL1M");
INSERT INTO teeth (teethID, Description, teethName) VALUES (28, "Lower Left 2nd Bicuspid", "LL2B");
INSERT INTO teeth (teethID, Description, teethName) VALUES (29, "Lower Left 1st Bicuspid", "LL1B");
INSERT INTO teeth (teethID, Description, teethName) VALUES (30, "Lower Left Cuspid", "LLCu");
INSERT INTO teeth (teethID, Description, teethName) VALUES (31, "Lower Left Lateral", "LLL");
INSERT INTO teeth (teethID, Description, teethName) VALUES (32, "Lower Left Central", "LLCe");

